"""Export a diet plan to a polished PDF using reportlab."""
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, PageBreak)


def diet_plan_pdf(plan: dict, user_name: str = "") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm,
                            title="NutriEase Diet Plan")
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Title"], textColor=colors.HexColor("#1f7a4d"),
                        fontSize=24, spaceAfter=6)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=colors.HexColor("#1f7a4d"),
                        fontSize=14, spaceBefore=14, spaceAfter=6)
    body = styles["BodyText"]
    small = ParagraphStyle("small", parent=body, fontSize=9, textColor=colors.grey)

    story = []
    story.append(Paragraph("NutriEase", h1))
    story.append(Paragraph(plan.get("title", "Personal Diet Plan"), styles["Heading1"]))
    if user_name:
        story.append(Paragraph(f"Prepared for: <b>{user_name}</b>", body))
    story.append(Paragraph(plan.get("summary", ""), body))
    story.append(Spacer(1, 8))

    macros = plan.get("macros", {})
    summary_data = [
        ["Daily calories", f"{plan.get('daily_calories', '-')} kcal"],
        ["Protein", f"{macros.get('protein_g', '-')} g"],
        ["Carbohydrates", f"{macros.get('carbs_g', '-')} g"],
        ["Fats", f"{macros.get('fats_g', '-')} g"],
        ["Hydration", f"{plan.get('hydration_liters', '-')} L / day"],
    ]
    t = Table(summary_data, colWidths=[5*cm, 6*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eaf6ee")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cfe7d8")),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cfe7d8")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)

    if plan.get("supplements"):
        story.append(Paragraph("Supplements", h2))
        for s in plan["supplements"]:
            story.append(Paragraph(f"&bull; {s}", body))

    if plan.get("tips"):
        story.append(Paragraph("Tips", h2))
        for s in plan["tips"]:
            story.append(Paragraph(f"&bull; {s}", body))

    story.append(PageBreak())
    story.append(Paragraph("7-Day Meal Plan", h1))

    for day in plan.get("days", []):
        story.append(Paragraph(day["day"], h2))
        rows = [["Meal", "Items", "kcal"]]
        total = 0
        for m in day["meals"]:
            rows.append([m["name"], "; ".join(m.get("items", [])), str(m.get("calories", ""))])
            total += int(m.get("calories", 0) or 0)
        rows.append(["Total", "", str(total)])
        tt = Table(rows, colWidths=[2.6*cm, 11*cm, 2*cm])
        tt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f7a4d")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#eaf6ee")),
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cfe7d8")),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cfe7d8")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("PADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(tt)
        story.append(Spacer(1, 6))

    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by NutriEase. This plan is informational and not a substitute for medical advice.", small))

    doc.build(story)
    return buf.getvalue()
